"""Script delegation — what `steer` redirects a classified read *to*.

This is the owner's own global rule made mechanical: write the script, write its test, the test
passes, *then* it runs on live data. Here that sequence is enforced rather than remembered, and
each step is recorded, so "I ran a script that handles this properly" becomes checkable instead of
a claim.

Three refusals, in order, and each exists because of a specific way the sequence gets skipped:

1. **No paired test** — the script never runs. "I'll add the test after" is how untested code
   reaches live data.
2. **Test failed** — the script never runs.
3. **Script changed after the test passed** — the script never runs. This is the subtle one: a
   green test on a since-edited script is evidence about a file that no longer exists. Digests
   are taken at test time and re-checked at run time.

The executed script gets an env allowlist and proxy variables pointing nowhere.

**That is not a sandbox, and this module no longer implies it is (#19).** A script can open a raw
socket, unset the proxy variables, exec another binary, or use a library that ignores proxies. The
allowlist does stop a handler inheriting credentials from the parent environment, which is worth
having on its own merits. A real boundary needs an OS sandbox or a separate uid, and neither
exists yet, so the record says `kind: env-allowlist-only` and carries the caveat rather than
letting a reader infer more.
"""

from __future__ import annotations

import os
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

from stop_guessing.artifacts.digest import bytes_digest, file_digest

TEMPLATE = '''"""{intent}

Generated by `stop-guessing delegate new`. This script — not the model — handles the data.

It receives artifact paths as argv and prints a RESULT. Whatever it prints is what enters model
context, so print findings, counts and summaries; never dump the source rows.
"""

import sys


def handle(paths: list[str]) -> str:
    # TODO: implement. Read the artifact here; return only what the caller actually needs.
    raise NotImplementedError("implement handle() before running this on live data")


if __name__ == "__main__":
    print(handle(sys.argv[1:]))
'''

TEST_TEMPLATE = '''"""Test for {name}. This must pass before the script touches live data."""

import {module}


def test_handle_is_implemented():
    try:
        {module}.handle([])
    except NotImplementedError:
        raise AssertionError(
            "handle() is still a stub — implement it before running on live data"
        ) from None
    except Exception:
        pass  # any other failure is the script's own business; it is implemented


def test_handle_returns_a_string_not_the_data():
    """A handler that returns the file's contents has not delegated anything."""
    out = {module}.handle([])
    assert isinstance(out, str)
'''

ENV_ALLOWLIST = ("PATH", "HOME", "LANG", "LC_ALL", "TMPDIR")


class DelegationRefused(Exception):
    """The sequence was not followed. Never caught internally."""


@dataclass
class Delegation:
    name: str
    script: Path
    test: Path
    intent: str
    script_digest: str | None = None
    test_digest: str | None = None
    test_result: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "path": str(self.script),
            "digest": self.script_digest,
            "test": str(self.test),
            "test_digest": self.test_digest,
            "test_result": self.test_result,
        }


def scaffold(directory: str | Path, name: str, intent: str) -> Delegation:
    """Write the script/test pair. Neither exists yet, so nothing can have skipped a step."""
    d = Path(directory)
    d.mkdir(parents=True, exist_ok=True)
    script = d / f"{name}.py"
    test = d / f"test_{name}.py"
    if script.exists():
        raise DelegationRefused(f"{script} already exists — edit it rather than scaffolding over it")
    script.write_text(TEMPLATE.format(intent=intent), encoding="utf-8")
    test.write_text(TEST_TEMPLATE.format(name=name, module=name), encoding="utf-8")
    return Delegation(name, script, test, intent,
                      file_digest(script), file_digest(test))


def run_test(deleg: Delegation, *, timeout: int = 120) -> dict:
    """Run the paired test and pin the digests it was run against."""
    if not deleg.test.is_file():
        raise DelegationRefused(
            f"no paired test at {deleg.test}. A script without a test does not touch live data."
        )
    res = subprocess.run(  # noqa: S603
        [sys.executable, "-m", "pytest", "-q", str(deleg.test)],
        capture_output=True, cwd=str(deleg.script.parent), timeout=timeout,
        env={**_clean_env(), "PYTHONPATH": str(deleg.script.parent)},
    )
    out = (res.stdout + res.stderr).decode("utf-8", "replace")
    deleg.script_digest = file_digest(deleg.script)
    deleg.test_digest = file_digest(deleg.test)
    deleg.test_result = {
        "passed": res.returncode == 0,
        "exit_code": res.returncode,
        "evidence_digest": bytes_digest(out.encode()),
        "tail": out.strip().splitlines()[-1] if out.strip() else "",
        "script_digest_at_test": deleg.script_digest,
    }
    return deleg.test_result


def run(deleg: Delegation, artifacts: list[str], *, timeout: int = 120) -> dict:
    """Execute the script over real artifacts — only if the whole sequence held."""
    if not deleg.test_result:
        raise DelegationRefused(
            "the paired test has not been run. Write the script, write the test, the test passes, "
            "THEN it runs on live data."
        )
    if not deleg.test_result.get("passed"):
        raise DelegationRefused(
            f"the paired test failed (exit {deleg.test_result.get('exit_code')}): "
            f"{deleg.test_result.get('tail', '')}"
        )
    current = file_digest(deleg.script)
    if current != deleg.test_result.get("script_digest_at_test"):
        raise DelegationRefused(
            f"{deleg.script} changed after its test passed "
            f"(tested {str(deleg.test_result.get('script_digest_at_test'))[:16]}…, "
            f"now {str(current)[:16]}…). A green test on a since-edited script is evidence "
            "about a file that no longer exists. Re-run the test."
        )

    res = subprocess.run(  # noqa: S603
        [sys.executable, str(deleg.script), *artifacts],
        capture_output=True, cwd=str(deleg.script.parent), timeout=timeout,
        env={**_clean_env(), "PYTHONPATH": str(deleg.script.parent),
             "SG_NETWORK": "deny", "http_proxy": "127.0.0.1:1", "https_proxy": "127.0.0.1:1"},
    )
    output = res.stdout.decode("utf-8", "replace")
    return {
        "exit_code": res.returncode,
        "output": output,
        "output_digest": bytes_digest(output.encode()),
        "argv_digest": bytes_digest(" ".join(artifacts).encode()),
        "stderr_tail": res.stderr.decode("utf-8", "replace").strip()[-300:],
        "sandbox": {
            # Honest naming (#19): an environment restriction, not a capability boundary.
            "kind": "env-allowlist-only",
            "network": "proxy-variables-only, NOT enforced",
            "env_allowlist": list(ENV_ALLOWLIST),
            "cwd": str(deleg.script.parent),
            "caveat": "a script can open raw sockets or exec another binary; this is not a sandbox",
        },
    }


def _clean_env() -> dict:
    """Only the allowlist survives — a delegated handler inherits no credentials."""
    return {k: v for k, v in os.environ.items() if k in ENV_ALLOWLIST}


# ── signing (bar posture) ────────────────────────────────────────────────────

SIG_SUFFIX = ".sig.json"


def sign_script(script: str | Path, key: bytes, keyid: str) -> dict:
    """Bind a signature to the script's CONTENT, not its path.

    Under `bar` a script must be signed with a key the model cannot reach. Signing the digest
    rather than the filename means editing the script invalidates the signature — moving or
    renaming it does not, which is the correct pair of behaviours: identity follows content.
    """
    import hashlib
    import hmac
    import json

    p = Path(script)
    digest = file_digest(p)
    if digest is None:
        raise DelegationRefused(f"cannot digest {p}")
    sig = hmac.new(key, f"sg-script-v1:{digest}".encode(), hashlib.sha256).hexdigest()
    record = {"scheme": "hmac-sha256", "keyid": keyid, "script_digest": digest, "sig": sig}
    Path(str(p) + SIG_SUFFIX).write_text(json.dumps(record, indent=2) + "\n", encoding="utf-8")
    return record


def verify_script(script: str | Path, key: bytes) -> tuple[bool, str]:
    """Returns (ok, reason). A missing or malformed signature is a finding, never a crash."""
    import hashlib
    import hmac
    import json

    p = Path(script)
    sig_path = Path(str(p) + SIG_SUFFIX)
    if not sig_path.is_file():
        return False, f"no signature beside {p.name}"
    try:
        rec = json.loads(sig_path.read_text(encoding="utf-8"))
        expected_digest = rec["script_digest"]
        claimed = rec["sig"]
    except (json.JSONDecodeError, KeyError, OSError) as exc:
        return False, f"malformed signature: {exc}"

    actual_digest = file_digest(p)
    if actual_digest != expected_digest:
        return False, (f"{p.name} changed since signing (signed {expected_digest[:16]}…, "
                       f"now {str(actual_digest)[:16]}…)")
    want = hmac.new(key, f"sg-script-v1:{expected_digest}".encode(), hashlib.sha256).hexdigest()
    if not hmac.compare_digest(want, claimed):
        return False, "signature does not verify under the supplied key"
    return True, f"verified under keyid {rec.get('keyid')}"


def emit_for_model(output: str, mode: str = "full", *, artifact_id: str = "") -> dict:
    """What actually reaches model context.

    Under `bar` the model receives a handle and a summary — never the bytes. The handle is what a
    later delegated script consumes, so work continues without the data ever entering context.
    """
    lines = output.splitlines()
    if mode == "full":
        return {"mode": "full", "content": output}
    summary = {
        "mode": mode,
        "handle": artifact_id or f"sha256:{bytes_digest(output.encode())[:16]}",
        "lines": len(lines),
        "bytes": len(output.encode()),
        "digest": bytes_digest(output.encode()),
    }
    if mode == "summary":
        summary["first_line_shape"] = (
            "".join("N" if c.isdigit() else "A" if c.isalpha() else c for c in lines[0][:60])
            if lines else ""
        )
    return summary
