"""Script delegation — what `steer` redirects a classified read *to*.

This is the owner's own global rule made mechanical: write the script, write its test, the test
passes, *then* it runs on live data. Here that sequence is enforced rather than remembered, and
each step is recorded, so "I ran a script that handles this properly" becomes checkable instead of
a claim.

Three refusals, in order, and each exists because of a specific way the sequence gets skipped:

1. **No paired test** — the script never runs. "I'll add the test after" is how untested code
   reaches live data.
2. **Test failed** — the script never runs.
3. **Script changed after the test passed** — the script never runs. This is the subtle one: a
   green test on a since-edited script is evidence about a file that no longer exists. Digests
   are taken at test time and re-checked at run time.

The executed script gets an env allowlist, and — since #54 — a real OS capability boundary from
`stop_guessing/sandbox.py`: macOS `sandbox-exec` or Linux `bwrap`, denying all network, writes
outside the declared outputs, and reads of the custody directory. Where a host offers neither, the
record says `mechanism: none` and keeps the old caveat, because a sandbox that silently degrades
to nothing is worse than none.

**The executed subject is a snapshot, not the path (#52).** The digest check and the execution
used to read the same mutable pathname twice, and a concurrent replacer drove through the window —
demonstrated live in `tests/test_adversarial.py`, where the payload ran. The checked bytes are now
copied once, re-digested, and the COPY is executed, at a path nothing else knows about.
"""

from __future__ import annotations

import os
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

from stop_guessing.artifacts.digest import bytes_digest, file_digest

TEMPLATE = '''"""{intent}

Generated by `stop-guessing delegate new`. This script — not the model — handles the data.

It receives artifact paths as argv and prints a RESULT. Whatever it prints is what enters model
context, so print findings, counts and summaries; never dump the source rows.
"""

import sys


def handle(paths: list[str]) -> str:
    # TODO: implement. Read the artifact here; return only what the caller actually needs.
    raise NotImplementedError("implement handle() before running this on live data")


if __name__ == "__main__":
    print(handle(sys.argv[1:]))
'''

TEST_TEMPLATE = '''"""Test for {name}. This must pass before the script touches live data."""

import {module}


def test_handle_is_implemented():
    try:
        {module}.handle([])
    except NotImplementedError:
        raise AssertionError(
            "handle() is still a stub — implement it before running on live data"
        ) from None
    except Exception:
        pass  # any other failure is the script's own business; it is implemented


def test_handle_returns_a_string_not_the_data():
    """A handler that returns the file's contents has not delegated anything."""
    out = {module}.handle([])
    assert isinstance(out, str)
'''

ENV_ALLOWLIST = ("PATH", "HOME", "LANG", "LC_ALL", "TMPDIR")


class DelegationRefused(Exception):
    """The sequence was not followed. Never caught internally."""


@dataclass
class Delegation:
    name: str
    script: Path
    test: Path
    intent: str
    script_digest: str | None = None
    test_digest: str | None = None
    test_result: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "path": str(self.script),
            "digest": self.script_digest,
            "test": str(self.test),
            "test_digest": self.test_digest,
            "test_result": self.test_result,
        }


def scaffold(directory: str | Path, name: str, intent: str) -> Delegation:
    """Write the script/test pair. Neither exists yet, so nothing can have skipped a step."""
    d = Path(directory)
    d.mkdir(parents=True, exist_ok=True)
    script = d / f"{name}.py"
    test = d / f"test_{name}.py"
    if script.exists():
        raise DelegationRefused(f"{script} already exists — edit it rather than scaffolding over it")
    script.write_text(TEMPLATE.format(intent=intent), encoding="utf-8")
    test.write_text(TEST_TEMPLATE.format(name=name, module=name), encoding="utf-8")
    return Delegation(name, script, test, intent,
                      file_digest(script), file_digest(test))


def run_test(deleg: Delegation, *, timeout: int = 120) -> dict:
    """Run the paired test and pin the digests it was run against."""
    if not deleg.test.is_file():
        raise DelegationRefused(
            f"no paired test at {deleg.test}. A script without a test does not touch live data."
        )
    # #51/#52 (SG-HARD-018/019). The digest was taken AFTER the test ran, so a hostile paired test
    # that rewrote the script had its REPLACEMENT certified: `run()` then compared the rewritten
    # bytes against a digest of the rewritten bytes, found them equal, and executed the payload.
    # Confirmed live by tests/test_adversarial.py before this change — the test wrote a marker file
    # and `run()` did not refuse.
    #
    # The subject is now pinned BEFORE the test is allowed near it, and a change across the test is
    # a refusal in its own right. A test may verify a script; it may not modify the script it is
    # verifying, and "the test passed" must mean "the test passed on THESE bytes".
    digest_before = file_digest(deleg.script)
    test_before = file_digest(deleg.test)

    res = subprocess.run(  # noqa: S603
        [sys.executable, "-m", "pytest", "-q", str(deleg.test)],
        capture_output=True, cwd=str(deleg.script.parent), timeout=timeout,
        env={**_clean_env(), "PYTHONPATH": str(deleg.script.parent)},
    )
    out = (res.stdout + res.stderr).decode("utf-8", "replace")

    digest_after = file_digest(deleg.script)
    if digest_after != digest_before:
        raise DelegationRefused(
            f"{deleg.script} was MODIFIED BY ITS OWN TEST "
            f"(before {str(digest_before)[:16]}…, after {str(digest_after)[:16]}…). "
            "A test may verify a script; it may not rewrite the script it is certifying. "
            "Nothing is executed and no result is recorded."
        )
    if file_digest(deleg.test) != test_before:
        raise DelegationRefused(
            f"{deleg.test} rewrote itself during the run. The evidence would describe a test "
            "that no longer exists."
        )

    deleg.script_digest = digest_before
    deleg.test_digest = test_before
    deleg.test_result = {
        "passed": res.returncode == 0,
        "exit_code": res.returncode,
        "evidence_digest": bytes_digest(out.encode()),
        "tail": out.strip().splitlines()[-1] if out.strip() else "",
        # The digest of the bytes the test was run AGAINST, not of whatever exists afterwards.
        "script_digest_at_test": digest_before,
    }
    return deleg.test_result


def run(deleg: Delegation, artifacts: list[str], *, timeout: int = 120) -> dict:
    """Execute the script over real artifacts — only if the whole sequence held."""
    if not deleg.test_result:
        raise DelegationRefused(
            "the paired test has not been run. Write the script, write the test, the test passes, "
            "THEN it runs on live data."
        )
    if not deleg.test_result.get("passed"):
        raise DelegationRefused(
            f"the paired test failed (exit {deleg.test_result.get('exit_code')}): "
            f"{deleg.test_result.get('tail', '')}"
        )
    current = file_digest(deleg.script)
    if current != deleg.test_result.get("script_digest_at_test"):
        raise DelegationRefused(
            f"{deleg.script} changed after its test passed "
            f"(tested {str(deleg.test_result.get('script_digest_at_test'))[:16]}…, "
            f"now {str(current)[:16]}…). A green test on a since-edited script is evidence "
            "about a file that no longer exists. Re-run the test."
        )

    # #54 (SG-HARD-021). The environment allowlist and proxy variables are advisory — this
    # module's own docstring said so — and the application claims leaned on "capability-
    # constrained" anyway. There is a real OS boundary now, and where the host cannot provide one
    # the record says `mechanism: none` rather than implying otherwise.
    # #52 (SG-HARD-019). The digest check above reads the path, and then execution reads it AGAIN
    # — a window a concurrent replacer can drive through, which tests/test_adversarial.py did:
    # the payload ran. A mutable pathname cannot be the security subject.
    #
    # So the checked bytes are SNAPSHOTTED and the snapshot is what executes. The copy is made
    # once, re-digested, and compared to the tested digest; nothing after that point can be
    # swapped, because the path being executed is one nothing else knows about.
    import shutil as _shutil
    import tempfile as _tempfile

    snap_dir = _tempfile.mkdtemp(prefix="sg-exec-")
    snapshot = Path(snap_dir) / deleg.script.name
    _shutil.copy2(deleg.script, snapshot)
    snap_digest = file_digest(snapshot)
    if snap_digest != deleg.test_result.get("script_digest_at_test"):
        _shutil.rmtree(snap_dir, ignore_errors=True)
        raise DelegationRefused(
            f"{deleg.script} changed while it was being snapshotted for execution "
            f"(tested {str(deleg.test_result.get('script_digest_at_test'))[:16]}…, "
            f"snapshot {str(snap_digest)[:16]}…). Nothing was executed."
        )

    from stop_guessing import sandbox as _sandbox

    argv, sb = _sandbox.wrap(
        [sys.executable, str(snapshot), *artifacts],
        reads=[str(deleg.script.parent), snap_dir, *artifacts],
        writes=[str(deleg.script.parent)],
    )
    res = subprocess.run(  # noqa: S603
        argv,
        capture_output=True, cwd=str(deleg.script.parent), timeout=timeout,
        env={**_clean_env(), "PYTHONPATH": str(deleg.script.parent),
             "SG_NETWORK": "deny", "http_proxy": "127.0.0.1:1", "https_proxy": "127.0.0.1:1"},
    )
    _shutil.rmtree(snap_dir, ignore_errors=True)
    output = res.stdout.decode("utf-8", "replace")
    return {
        "exit_code": res.returncode,
        "output": output,
        "output_digest": bytes_digest(output.encode()),
        "argv_digest": bytes_digest(" ".join(artifacts).encode()),
        "stderr_tail": res.stderr.decode("utf-8", "replace").strip()[-300:],
        # The record states the boundary that was ACTUALLY applied. #19 named this honestly when
        # there was no boundary; #54 supplied one, so the caveat must not outlive the defect —
        # a record that still said "this is not a sandbox" under an enforced profile would be
        # wrong in the other direction, and equally useless to an auditor.
        "sandbox": {
            "mechanism": sb.mechanism,
            "enforced": sb.enforced,
            "boundary": sb.detail,
            "kind": "os-capability-boundary" if sb.enforced else "env-allowlist-only",
            "network": "denied by the OS" if sb.enforced
                       else "proxy-variables-only, NOT enforced",
            "env_allowlist": list(ENV_ALLOWLIST),
            "cwd": str(deleg.script.parent),
            "caveat": (
                "deny-listed, not deny-by-default: network, writes outside the declared outputs, "
                "and reads of the custody directory are refused by the OS. A container is still "
                "stronger."
                if sb.enforced else
                "a script can open raw sockets or exec another binary; this is not a sandbox"
            ),
        },
    }


def _clean_env() -> dict:
    """Only the allowlist survives — a delegated handler inherits no credentials."""
    return {k: v for k, v in os.environ.items() if k in ENV_ALLOWLIST}


# ── signing (bar posture) ────────────────────────────────────────────────────

SIG_SUFFIX = ".sig.json"


def sign_script(script: str | Path, key: bytes, keyid: str) -> dict:
    """Bind a signature to the script's CONTENT, not its path.

    Under `bar` a script must be signed with a key the model cannot reach. Signing the digest
    rather than the filename means editing the script invalidates the signature — moving or
    renaming it does not, which is the correct pair of behaviours: identity follows content.
    """
    import hashlib
    import hmac
    import json

    p = Path(script)
    digest = file_digest(p)
    if digest is None:
        raise DelegationRefused(f"cannot digest {p}")
    sig = hmac.new(key, f"sg-script-v1:{digest}".encode(), hashlib.sha256).hexdigest()
    record = {"scheme": "hmac-sha256", "keyid": keyid, "script_digest": digest, "sig": sig}
    Path(str(p) + SIG_SUFFIX).write_text(json.dumps(record, indent=2) + "\n", encoding="utf-8")
    return record


def verify_script(script: str | Path, key: bytes) -> tuple[bool, str]:
    """Returns (ok, reason). A missing or malformed signature is a finding, never a crash."""
    import hashlib
    import hmac
    import json

    p = Path(script)
    sig_path = Path(str(p) + SIG_SUFFIX)
    if not sig_path.is_file():
        return False, f"no signature beside {p.name}"
    try:
        rec = json.loads(sig_path.read_text(encoding="utf-8"))
        expected_digest = rec["script_digest"]
        claimed = rec["sig"]
    except (json.JSONDecodeError, KeyError, OSError) as exc:
        return False, f"malformed signature: {exc}"

    actual_digest = file_digest(p)
    if actual_digest != expected_digest:
        return False, (f"{p.name} changed since signing (signed {expected_digest[:16]}…, "
                       f"now {str(actual_digest)[:16]}…)")
    want = hmac.new(key, f"sg-script-v1:{expected_digest}".encode(), hashlib.sha256).hexdigest()
    if not hmac.compare_digest(want, claimed):
        return False, "signature does not verify under the supplied key"
    return True, f"verified under keyid {rec.get('keyid')}"


def emit_for_model(output: str, mode: str = "full", *, artifact_id: str = "") -> dict:
    """What actually reaches model context.

    Under `bar` the model receives a handle and a summary — never the bytes. The handle is what a
    later delegated script consumes, so work continues without the data ever entering context.
    """
    lines = output.splitlines()
    if mode == "full":
        return {"mode": "full", "content": output}
    summary = {
        "mode": mode,
        "handle": artifact_id or f"sha256:{bytes_digest(output.encode())[:16]}",
        "lines": len(lines),
        "bytes": len(output.encode()),
        "digest": bytes_digest(output.encode()),
    }
    if mode == "summary":
        summary["first_line_shape"] = (
            "".join("N" if c.isdigit() else "A" if c.isalpha() else c for c in lines[0][:60])
            if lines else ""
        )
    return summary
