"""Script delegation — what `steer` redirects a classified read *to*.

This is the owner's own global rule made mechanical: write the script, write its test, the test
passes, *then* it runs on live data. Here that sequence is enforced rather than remembered, and
each step is recorded, so "I ran a script that handles this properly" becomes checkable instead of
a claim.

Three refusals, in order, and each exists because of a specific way the sequence gets skipped:

1. **No paired test** — the script never runs. "I'll add the test after" is how untested code
   reaches live data.
2. **Test failed** — the script never runs.
3. **Script changed after the test passed** — the script never runs. This is the subtle one: a
   green test on a since-edited script is evidence about a file that no longer exists. Digests
   are taken at test time and re-checked at run time.

The executed script gets `network=deny` and an env allowlist, so a delegated handler cannot become
the egress it was meant to avoid.
"""

from __future__ import annotations

import os
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

from stop_guessing.artifacts.digest import bytes_digest, file_digest

TEMPLATE = '''"""{intent}

Generated by `stop-guessing delegate new`. This script — not the model — handles the data.

It receives artifact paths as argv and prints a RESULT. Whatever it prints is what enters model
context, so print findings, counts and summaries; never dump the source rows.
"""

import sys


def handle(paths: list[str]) -> str:
    # TODO: implement. Read the artifact here; return only what the caller actually needs.
    raise NotImplementedError("implement handle() before running this on live data")


if __name__ == "__main__":
    print(handle(sys.argv[1:]))
'''

TEST_TEMPLATE = '''"""Test for {name}. This must pass before the script touches live data."""

import {module}


def test_handle_is_implemented():
    try:
        {module}.handle([])
    except NotImplementedError:
        raise AssertionError(
            "handle() is still a stub — implement it before running on live data"
        ) from None
    except Exception:
        pass  # any other failure is the script's own business; it is implemented


def test_handle_returns_a_string_not_the_data():
    """A handler that returns the file's contents has not delegated anything."""
    out = {module}.handle([])
    assert isinstance(out, str)
'''

ENV_ALLOWLIST = ("PATH", "HOME", "LANG", "LC_ALL", "TMPDIR")


class DelegationRefused(Exception):
    """The sequence was not followed. Never caught internally."""


@dataclass
class Delegation:
    name: str
    script: Path
    test: Path
    intent: str
    script_digest: str | None = None
    test_digest: str | None = None
    test_result: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "path": str(self.script),
            "digest": self.script_digest,
            "test": str(self.test),
            "test_digest": self.test_digest,
            "test_result": self.test_result,
        }


def scaffold(directory: str | Path, name: str, intent: str) -> Delegation:
    """Write the script/test pair. Neither exists yet, so nothing can have skipped a step."""
    d = Path(directory)
    d.mkdir(parents=True, exist_ok=True)
    script = d / f"{name}.py"
    test = d / f"test_{name}.py"
    if script.exists():
        raise DelegationRefused(f"{script} already exists — edit it rather than scaffolding over it")
    script.write_text(TEMPLATE.format(intent=intent), encoding="utf-8")
    test.write_text(TEST_TEMPLATE.format(name=name, module=name), encoding="utf-8")
    return Delegation(name, script, test, intent,
                      file_digest(script), file_digest(test))


def run_test(deleg: Delegation, *, timeout: int = 120) -> dict:
    """Run the paired test and pin the digests it was run against."""
    if not deleg.test.is_file():
        raise DelegationRefused(
            f"no paired test at {deleg.test}. A script without a test does not touch live data."
        )
    res = subprocess.run(  # noqa: S603
        [sys.executable, "-m", "pytest", "-q", str(deleg.test)],
        capture_output=True, cwd=str(deleg.script.parent), timeout=timeout,
        env={**_clean_env(), "PYTHONPATH": str(deleg.script.parent)},
    )
    out = (res.stdout + res.stderr).decode("utf-8", "replace")
    deleg.script_digest = file_digest(deleg.script)
    deleg.test_digest = file_digest(deleg.test)
    deleg.test_result = {
        "passed": res.returncode == 0,
        "exit_code": res.returncode,
        "evidence_digest": bytes_digest(out.encode()),
        "tail": out.strip().splitlines()[-1] if out.strip() else "",
        "script_digest_at_test": deleg.script_digest,
    }
    return deleg.test_result


def run(deleg: Delegation, artifacts: list[str], *, timeout: int = 120) -> dict:
    """Execute the script over real artifacts — only if the whole sequence held."""
    if not deleg.test_result:
        raise DelegationRefused(
            "the paired test has not been run. Write the script, write the test, the test passes, "
            "THEN it runs on live data."
        )
    if not deleg.test_result.get("passed"):
        raise DelegationRefused(
            f"the paired test failed (exit {deleg.test_result.get('exit_code')}): "
            f"{deleg.test_result.get('tail', '')}"
        )
    current = file_digest(deleg.script)
    if current != deleg.test_result.get("script_digest_at_test"):
        raise DelegationRefused(
            f"{deleg.script} changed after its test passed "
            f"(tested {str(deleg.test_result.get('script_digest_at_test'))[:16]}…, "
            f"now {str(current)[:16]}…). A green test on a since-edited script is evidence "
            "about a file that no longer exists. Re-run the test."
        )

    res = subprocess.run(  # noqa: S603
        [sys.executable, str(deleg.script), *artifacts],
        capture_output=True, cwd=str(deleg.script.parent), timeout=timeout,
        env={**_clean_env(), "PYTHONPATH": str(deleg.script.parent),
             "SG_NETWORK": "deny", "http_proxy": "127.0.0.1:1", "https_proxy": "127.0.0.1:1"},
    )
    output = res.stdout.decode("utf-8", "replace")
    return {
        "exit_code": res.returncode,
        "output": output,
        "output_digest": bytes_digest(output.encode()),
        "argv_digest": bytes_digest(" ".join(artifacts).encode()),
        "stderr_tail": res.stderr.decode("utf-8", "replace").strip()[-300:],
        "sandbox": {"network": "deny", "env_allowlist": list(ENV_ALLOWLIST),
                    "cwd": str(deleg.script.parent)},
    }


def _clean_env() -> dict:
    """Only the allowlist survives — a delegated handler inherits no credentials."""
    return {k: v for k, v in os.environ.items() if k in ENV_ALLOWLIST}
